//! Netlist Export (SPICE Format)
//!
//! Generates SPICE netlists from the routing graph for circuit simulation.
//! SPICE (Simulation Program with Integrated Circuit Emphasis) is the industry
//! standard format for analog circuit simulation.
//!
//! # Four-File SPICE Suite (v0.2.1)
//!
//! Generates four specialized SPICE files for different use cases:
//! - circuit.sp: Pure DUT (Device Under Test) with no stimulus
//! - dc.sp: DC operating point test with voltage sources from net declarations
//! - ac.sp: AC frequency response with small-signal analysis (NEW in v0.2.1)
//! - tran.sp: Transient analysis with pulsed stimulus for waveform plotting
//!
//! # Module layout
//!
//! - `types`: Shared data structures (`ParasiticElement`, `PhysicalNetlistGraph`, `StimulusMode`)
//! - `parasitics`: Trace parasitic extraction into a `PhysicalNetlistGraph`
//! - `circuit_body`: Reusable DUT body (subcircuits, nets, components)
//! - `extracted_devices`: SPICE cards for extracted physical devices and parasitics
//! - `stimulus`: DC/AC/transient stimulus generation
//! - `subcircuit`: Typed-AST to SPICE `.subckt` code generation

pub mod circuit_body;
pub mod extracted_devices;
pub mod parasitics;
pub mod stimulus;
pub mod subcircuit;
pub mod types;

use std::path::Path;

use hwc_compiler::SymbolTable;
use hwc_engine::HardwareSpace;
use hwc_parser::SpaceDefinition;
use hwc_types::UnitRegistry;

use parasitics::build_physical_netlist_graph;
use stimulus::generate_stimulus;
use types::StimulusMode;

/// Generate SPICE netlist suite (3 files in spice/ subdirectory)
pub fn export(
    space: &HardwareSpace,
    symbol_table: &SymbolTable,
    output_dir: &Path,
    physical_netlist: Option<&types::PhysicalNetlist>,
    space_def: Option<&SpaceDefinition>,
    unit_registry: &UnitRegistry,
) -> Result<(), Box<dyn std::error::Error>> {
    // Create spice subdirectory
    let spice_dir = output_dir.join("spice");
    std::fs::create_dir_all(&spice_dir)?;

    // Extract substrate_net from profile or space ground net classification
    let substrate_net_compact: compact_str::CompactString = space_def
        .and_then(|sd| sd.profile.as_ref())
        .and_then(|pname| symbol_table.get_profile(&pname.name).ok())
        .and_then(|profile| profile.substrate_net())
        .or_else(|| {
            space
                .net_classifications
                .iter()
                .find(|(_, &c)| c == hwc_engine::space::NetClassification::Ground)
                .map(|(name, _)| name.clone())
        })
        .unwrap_or_else(|| "BULK".into());
    let substrate_net = substrate_net_compact.as_str();

    // Resolve the testbench that drives AC/transient stimulus generation.
    // Honors the Zero-Hidden-Fallbacks mandate: AC/transient exporters fail loudly
    // when no `ac:`/`tran:` configuration is provided.
    let test_def = space_def
        .map(|sd| symbol_table.find_test_for_space(sd.name.as_str()))
        .flatten();

    // Build physical netlist graph with integrated parasitics (used by both circuit and stimulus)
    let physical_graph =
        build_physical_netlist_graph(space, symbol_table, physical_netlist, substrate_net)?;

    // Generate circuit body (reused by all variants)
    let circuit_body = circuit_body::generate_circuit_body(
        space,
        symbol_table,
        physical_netlist,
        &physical_graph,
        unit_registry,
    )?;

    // 1. Raw circuit (DUT only - no stimulus)
    let circuit_content = format!(
        "* Hardware Script Pure Circuit (DUT)\n\
         * Space: {}\n\
         * Generated by hwc v{}\n\
         * Format: SPICE3\n\n\
         {}\
         .end\n",
        space.name, env!("CARGO_PKG_VERSION"), circuit_body
    );
    std::fs::write(spice_dir.join("circuit.sp"), circuit_content)?;

    // 2. DC operating point / sweep test
    let has_dc_config = test_def.map(|t| t.configs.iter().any(|c| c.name == "dc")).unwrap_or(false);
    let dc_title = if has_dc_config {
        "DC Sweep Analysis Test"
    } else {
        "DC Operating Point Test"
    };

    let dc_stimulus = generate_stimulus(
        space_def,
        StimulusMode::DcOperatingPoint,
        physical_netlist,
        unit_registry,
        &physical_graph,
        Some(symbol_table),
        test_def,
    )?;
    let dc_content = format!(
        "* Hardware Script {}\n\
         * Space: {}\n\
         * Generated by hwc v{}\n\
         * Format: SPICE3\n\n\
         .include \"circuit.sp\"\n\n\
         * ========================================\n\
         * STIMULUS & ANALYSIS\n\
         * ========================================\n\
         {}\
         .end\n",
        dc_title, space.name, env!("CARGO_PKG_VERSION"), dc_stimulus
    );
    std::fs::write(spice_dir.join("dc.sp"), dc_content)?;

    // 3. AC frequency response test
    let has_ac_config = test_def.map(|t| t.configs.iter().any(|c| c.name == "ac")).unwrap_or(false);
    if has_ac_config {
        let ac_stimulus = generate_stimulus(
            space_def,
            StimulusMode::AcFrequencyResponse,
            physical_netlist,
            unit_registry,
            &physical_graph,
            Some(symbol_table),
            test_def,
        )?;
        let ac_content = format!(
            "* Hardware Script AC Frequency Response Test\n\
             * Space: {}\n\
             * Generated by hwc v{}\n\
             * Format: SPICE3\n\n\
             .include \"circuit.sp\"\n\n\
             * ========================================\n\
             * STIMULUS & ANALYSIS\n\
             * ========================================\n\
             {}\
             .end\n",
            space.name, env!("CARGO_PKG_VERSION"), ac_stimulus
        );
        std::fs::write(spice_dir.join("ac.sp"), ac_content)?;
    }

    // 4. Transient waveform test
    let has_tran_config = test_def.map(|t| t.configs.iter().any(|c| c.name == "tran")).unwrap_or(false);
    if has_tran_config {
        let tran_stimulus = generate_stimulus(
            space_def,
            StimulusMode::Transient,
            physical_netlist,
            unit_registry,
            &physical_graph,
            Some(symbol_table),
            test_def,
        )?;
        let tran_content = format!(
            "* Hardware Script Transient Waveform Test\n\
             * Space: {}\n\
             * Generated by hwc v{}\n\
             * Format: SPICE3\n\n\
             .include \"circuit.sp\"\n\n\
             * ========================================\n\
             * STIMULUS & ANALYSIS\n\
             * ========================================\n\
             {}\
             .end\n",
            space.name, env!("CARGO_PKG_VERSION"), tran_stimulus
        );
        std::fs::write(spice_dir.join("tran.sp"), tran_content)?;
    }

    // Report to user
    let component_count = space.netlist.component_count();
    let pour_net_count = space.pours.iter().filter(|p| p.net.is_some()).count();
    let total_nets = space.netlist.num_nets() + pour_net_count;

    println!(
        "✅ SPICE Suite: {}/spice/ ({} components, {} nets)",
        output_dir.display(),
        component_count,
        total_nets
    );
    println!("   ├─ circuit.sp (raw DUT)");
    if has_dc_config {
        println!("   ├─ dc.sp (DC sweep analysis)");
    } else {
        println!("   ├─ dc.sp (DC operating point)");
    }
    if has_ac_config {
        println!("   ├─ ac.sp (AC frequency response)");
    }
    if has_tran_config {
        println!("   └─ tran.sp (transient waveform)");
    }

    Ok(())
}
