//! Netlist Export (SPICE Format)
//!
//! Generates SPICE netlists from the routing graph for circuit simulation.
//! SPICE (Simulation Program with Integrated Circuit Emphasis) is the industry
//! standard format for analog circuit simulation.
//!
//! # Three-File SPICE Suite
//!
//! Generates three specialized SPICE files for different use cases:
//! - circuit.sp: Pure DUT (Device Under Test) with no stimulus
//! - dc.sp: DC operating point test with voltage sources from net declarations
//! - tran.sp: Transient analysis with pulsed stimulus for waveform plotting
//!
//! # Module layout
//!
//! - `types`: Shared data structures (`ParasiticElement`, `PhysicalNetlistGraph`, `StimulusMode`)
//! - `parasitics`: Trace parasitic extraction into a `PhysicalNetlistGraph`
//! - `circuit_body`: Reusable DUT body (subcircuits, nets, components)
//! - `extracted_devices`: SPICE cards for extracted physical devices and parasitics
//! - `stimulus`: DC/transient stimulus generation
//! - `subcircuit`: Typed-AST to SPICE `.subckt` code generation

pub mod circuit_body;
pub mod extracted_devices;
pub mod parasitics;
pub mod stimulus;
pub mod subcircuit;
pub mod types;

use std::path::Path;

use hwc_compiler::SymbolTable;
use hwc_engine::HardwareSpace;
use hwc_parser::SpaceDefinition;
use hwc_types::UnitRegistry;

use parasitics::build_physical_netlist_graph;
use stimulus::generate_stimulus;
use types::StimulusMode;

/// Generate SPICE netlist suite (3 files in spice/ subdirectory)
pub fn export(
    space: &HardwareSpace,
    symbol_table: &SymbolTable,
    output_dir: &Path,
    physical_netlist: Option<&hwc_compiler::alignment::PhysicalNetlist>,
    space_def: Option<&SpaceDefinition>,
    unit_registry: &UnitRegistry,
) -> Result<(), Box<dyn std::error::Error>> {
    // Create spice subdirectory
    let spice_dir = output_dir.join("spice");
    std::fs::create_dir_all(&spice_dir)?;

    // Extract substrate_net from profile (v0.2.2 Stage 1) - REQUIRED, no fallback
    let substrate_net = if let Some(sd) = space_def {
        if let Some(profile_name) = &sd.profile {
            let profile = symbol_table.get_profile(&profile_name.name).map_err(|e| {
                format!(
                    "Profile '{}' referenced in space but not found: {}",
                    profile_name.name, e
                )
            })?;

            profile
                .substrate_net
                .as_ref()
                .ok_or_else(|| {
                    format!(
                        "Profile '{}' missing REQUIRED field 'substrate_net'.\n\
                     \n\
                     Add to profile definition:\n\
                     \n\
                     profile {}:\n\
                         substrate_net: BULK  # For IC designs\n\
                         # OR\n\
                         substrate_net: GND   # For PCB designs\n\
                     \n\
                     This specifies the net that parasitic capacitances connect to.\n\
                     For integrated circuits, typically BULK or SUB.\n\
                     For PCB designs, typically GND.",
                        profile_name.name, profile_name.name
                    )
                })?
                .as_str()
        } else {
            return Err(format!(
                "Space '{}' has no profile defined. Add 'profile: <ProfileName>' to the space definition.\n\
                 \n\
                 The profile must declare 'substrate_net:' to specify where parasitic capacitances connect.",
                space.name
            )
            .into());
        }
    } else {
        return Err(
            "No space definition available for netlist export. Internal compiler error.".into(),
        );
    };

    // Build physical netlist graph with integrated parasitics (used by both circuit and stimulus)
    let physical_graph =
        build_physical_netlist_graph(space, symbol_table, physical_netlist, substrate_net)?;

    // Generate circuit body (reused by all variants)
    let circuit_body = circuit_body::generate_circuit_body(
        space,
        symbol_table,
        physical_netlist,
        &physical_graph,
    )?;

    // 1. Raw circuit (DUT only - no stimulus)
    let circuit_content = format!(
        "* Hardware Script Pure Circuit (DUT)\n\
         * Space: {}\n\
         * Generated by hwc v0.1.6\n\
         * Format: SPICE3\n\n\
         {}\
         .end\n",
        space.name, circuit_body
    );
    std::fs::write(spice_dir.join("circuit.sp"), circuit_content)?;

    // 2. DC operating point test
    let dc_stimulus = generate_stimulus(
        space_def,
        StimulusMode::DcOperatingPoint,
        physical_netlist,
        unit_registry,
        &physical_graph,
        Some(symbol_table),
    );
    let dc_content = format!(
        "* Hardware Script DC Operating Point Test\n\
         * Space: {}\n\
         * Generated by hwc v0.1.6\n\
         * Format: SPICE3\n\n\
         .include \"circuit.sp\"\n\n\
         * ========================================\n\
         * STIMULUS & ANALYSIS\n\
         * ========================================\n\
         {}\
         .end\n",
        space.name, dc_stimulus
    );
    std::fs::write(spice_dir.join("dc.sp"), dc_content)?;

    // 3. Transient waveform test
    let tran_stimulus = generate_stimulus(
        space_def,
        StimulusMode::Transient,
        physical_netlist,
        unit_registry,
        &physical_graph,
        Some(symbol_table),
    );
    let tran_content = format!(
        "* Hardware Script Transient Waveform Test\n\
         * Space: {}\n\
         * Generated by hwc v0.1.6\n\
         * Format: SPICE3\n\n\
         .include \"circuit.sp\"\n\n\
         * ========================================\n\
         * STIMULUS & ANALYSIS\n\
         * ========================================\n\
         {}\
         .end\n",
        space.name, tran_stimulus
    );
    std::fs::write(spice_dir.join("tran.sp"), tran_content)?;

    // Report to user
    let component_count = space.netlist.component_count();
    let pour_net_count = space.pours.iter().filter(|p| p.net.is_some()).count();
    let total_nets = space.netlist.num_nets() + pour_net_count;

    println!(
        "✅ SPICE Suite: {}/spice/ ({} components, {} nets)",
        output_dir.display(),
        component_count,
        total_nets
    );
    println!("   ├─ circuit.sp (raw DUT)");
    println!("   ├─ dc.sp (DC operating point)");
    println!("   └─ tran.sp (transient waveform)");

    Ok(())
}
