//! Netlist Export (SPICE Format)
//!
//! Generates SPICE netlists from the routing graph for circuit simulation.
//! SPICE (Simulation Program with Integrated Circuit Emphasis) is the industry
//! standard format for analog circuit simulation.
//!
//! # Three-File SPICE Suite
//!
//! Generates three specialized SPICE files for different use cases:
//! - circuit.sp: Pure DUT (Device Under Test) with no stimulus
//! - dc.sp: DC operating point test with voltage sources from net declarations
//! - tran.sp: Transient analysis with pulsed stimulus for waveform plotting

use compact_str::CompactString;
use hwc_compiler::SymbolTable;
use hwc_engine::HardwareSpace;
use hwc_parser::SpiceParameterStyle;
use rustc_hash::FxHashMap;
use std::path::Path;

/// Parasitic element extracted from routing
#[derive(Debug, Clone)]
enum ParasiticElement {
    TraceResistor {
        name: String,
        node_a: String,
        node_b: String,
        value_ohms: f64,
    },
    GroundCapacitance {
        name: String,
        node: String,
        ref_node: String,
        value_farads: f64,
    },
}

/// Physical netlist graph with integrated parasitics
#[derive(Debug, Clone)]
struct PhysicalNetlistGraph {
    /// Device terminal connections (terminal -> physical node)
    device_nodes: FxHashMap<(String, String), String>, // (device_name, terminal) -> node_id
    /// Parasitic elements
    parasitics: Vec<ParasiticElement>,
    /// Net entry points (top-level net name -> entry node)
    net_entry_points: FxHashMap<String, String>,
}

/// Stimulus generation mode for SPICE export
#[derive(Debug, Clone, Copy)]
enum StimulusMode {
    /// DC voltage sources with .op directive
    DcOperatingPoint,
    /// Pulsed voltage sources with .tran directive
    Transient,
}

/// Generate SPICE netlist suite (3 files in spice/ subdirectory)
pub fn export(
    space: &HardwareSpace,
    symbol_table: &SymbolTable,
    output_dir: &Path,
    physical_netlist: Option<&hwc_compiler::alignment::PhysicalNetlist>,
    space_def: Option<&hwc_parser::SpaceDefinition>,
    unit_registry: &hwc_types::UnitRegistry,
) -> Result<(), Box<dyn std::error::Error>> {
    // Create spice subdirectory
    let spice_dir = output_dir.join("spice");
    std::fs::create_dir_all(&spice_dir)?;

    // Extract substrate_net from profile (v0.2.2 Stage 1) - REQUIRED, no fallback
    let substrate_net = if let Some(sd) = space_def {
        if let Some(profile_name) = &sd.profile {
            let profile = symbol_table.get_profile(&profile_name.name)
                .map_err(|e| format!("Profile '{}' referenced in space but not found: {}", profile_name.name, e))?;
            
            profile.substrate_net.as_ref()
                .ok_or_else(|| format!(
                    "Profile '{}' missing REQUIRED field 'substrate_net'.\n\
                     \n\
                     Add to profile definition:\n\
                     \n\
                     profile {}:\n\
                         substrate_net: BULK  # For IC designs\n\
                         # OR\n\
                         substrate_net: GND   # For PCB designs\n\
                     \n\
                     This specifies the net that parasitic capacitances connect to.\n\
                     For integrated circuits, typically BULK or SUB.\n\
                     For PCB designs, typically GND.",
                    profile_name.name, profile_name.name
                ))?
                .as_str()
        } else {
            return Err(format!(
                "Space '{}' has no profile defined. Add 'profile: <ProfileName>' to the space definition.\n\
                 \n\
                 The profile must declare 'substrate_net:' to specify where parasitic capacitances connect.",
                space.name
            ).into());
        }
    } else {
        return Err("No space definition available for netlist export. Internal compiler error.".into());
    };

    // Build physical netlist graph with integrated parasitics (used by both circuit and stimulus)
    let physical_graph = build_physical_netlist_graph(space, symbol_table, physical_netlist, substrate_net)?;

    // Generate circuit body (reused by all variants)
    let circuit_body = generate_circuit_body(space, symbol_table, physical_netlist, &physical_graph)?;

    // 1. Raw circuit (DUT only - no stimulus)
    let circuit_content = format!(
        "* Hardware Script Pure Circuit (DUT)\n\
         * Space: {}\n\
         * Generated by hwc v0.1.6\n\
         * Format: SPICE3\n\n\
         {}\
         .end\n",
        space.name, circuit_body
    );
    std::fs::write(spice_dir.join("circuit.sp"), circuit_content)?;

    // 2. DC operating point test
    let dc_stimulus = generate_stimulus(space_def, StimulusMode::DcOperatingPoint, physical_netlist, unit_registry, &physical_graph, Some(symbol_table));
    let dc_content = format!(
        "* Hardware Script DC Operating Point Test\n\
         * Space: {}\n\
         * Generated by hwc v0.1.6\n\
         * Format: SPICE3\n\n\
         .include \"circuit.sp\"\n\n\
         * ========================================\n\
         * STIMULUS & ANALYSIS\n\
         * ========================================\n\
         {}\
         .end\n",
        space.name, dc_stimulus
    );
    std::fs::write(spice_dir.join("dc.sp"), dc_content)?;

    // 3. Transient waveform test
    let tran_stimulus = generate_stimulus(space_def, StimulusMode::Transient, physical_netlist, unit_registry, &physical_graph, Some(symbol_table));
    let tran_content = format!(
        "* Hardware Script Transient Waveform Test\n\
         * Space: {}\n\
         * Generated by hwc v0.1.6\n\
         * Format: SPICE3\n\n\
         .include \"circuit.sp\"\n\n\
         * ========================================\n\
         * STIMULUS & ANALYSIS\n\
         * ========================================\n\
         {}\
         .end\n",
        space.name, tran_stimulus
    );
    std::fs::write(spice_dir.join("tran.sp"), tran_content)?;

    // Report to user
    let component_count = space.netlist.component_count();
    let pour_net_count = space.pours.iter().filter(|p| p.net.is_some()).count();
    let total_nets = space.netlist.num_nets() + pour_net_count;

    println!(
        "✅ SPICE Suite: {}/spice/ ({} components, {} nets)",
        output_dir.display(),
        component_count,
        total_nets
    );
    println!("   ├─ circuit.sp (raw DUT)");
    println!("   ├─ dc.sp (DC operating point)");
    println!("   └─ tran.sp (transient waveform)");

    Ok(())
}

/// Extract trace parasitics (R, C, L) from routed segments and build physical netlist graph
fn build_physical_netlist_graph(
    space: &HardwareSpace,
    _symbol_table: &SymbolTable,
    physical_netlist: Option<&hwc_compiler::alignment::PhysicalNetlist>,
    substrate_net: &str,
) -> Result<PhysicalNetlistGraph, Box<dyn std::error::Error>> {
    let mut graph = PhysicalNetlistGraph {
        device_nodes: FxHashMap::default(),
        parasitics: Vec::new(),
        net_entry_points: FxHashMap::default(),
    };
    
    eprintln!("[NETLIST PARASITIC DEBUG] analytic_routes.len() = {}", space.analytic_routes.len());
    
    if space.analytic_routes.is_empty() {
        eprintln!("[NETLIST PARASITIC DEBUG] No analytic routes - skipping parasitic extraction");
        // No routing - use logical net names directly
        if let Some(netlist) = physical_netlist {
            for device in &netlist.devices {
                for (terminal, net_name) in &device.terminals {
                    let key = (device.name.to_string(), terminal.to_string());
                    graph.device_nodes.insert(key, net_name.clone());
                }
            }
        }
        return Ok(graph);
    }
    
    eprintln!("[NETLIST PARASITIC DEBUG] Found {} analytic routes - proceeding with parasitic extraction", space.analytic_routes.len());
    
    // Physical constants
    const EPS_0: f64 = 8.854187817e-12; // F/m
    
    // Build net-to-segments mapping
    let mut net_segments: FxHashMap<String, Vec<(usize, usize)>> = FxHashMap::default();
    for (trace_idx, trace) in space.analytic_routes.iter().enumerate() {
        for seg_idx in 0..trace.segments.len() {
            net_segments.entry(trace.net_name.to_string())
                .or_default()
                .push((trace_idx, seg_idx));
        }
    }
    
    eprintln!("[NETLIST PARASITIC DEBUG] Built net_segments map with {} nets", net_segments.len());
    
    // For each net with routing, create physical node chain
    for (net_name, segments) in &net_segments {
        eprintln!("[NETLIST PARASITIC DEBUG] Processing net '{}' with {} segments", net_name, segments.len());
        
        if segments.is_empty() {
            graph.net_entry_points.insert(net_name.clone(), net_name.clone());
            continue;
        }
        
        // Entry point is the first segment start node
        let entry_node = format!("n{}_entry", net_name);
        graph.net_entry_points.insert(net_name.clone(), entry_node.clone());
        
        let mut prev_node = entry_node;
        
        // Extract parasitics for each segment
        for (seg_num, &(trace_idx, seg_idx)) in segments.iter().enumerate() {
            let trace = &space.analytic_routes[trace_idx];
            let segment = &trace.segments[seg_idx];
            
            // **Stage 1 Node Topology:**
            // Entry point → Trace R → Logical net name
            // The final node for this net's parasitic chain is the logical net name itself
            let node_end = net_name.clone();
            
            // Extract resistance
            if let Some(material_props) = space.material_registry.get_physical_props(trace.material) {
                eprintln!("[NETLIST PARASITIC DEBUG] Net '{}' seg {}: Found material properties", net_name, seg_num);
                
                if let Some(resistivity) = material_props.get("resistivity") {
                    eprintln!("[NETLIST PARASITIC DEBUG] Net '{}' seg {}: resistivity = {}", net_name, seg_num, resistivity);
                    
                    let thickness_nm = trace.cross_section.thickness_nm;
                    let width_nm = trace.cross_section.width_nm;
                    
                    let dx = (segment.end.x - segment.start.x) as f64;
                    let dy = (segment.end.y - segment.start.y) as f64;
                    let dz = (segment.end.z - segment.start.z) as f64;
                    let length_m = ((dx * dx + dy * dy + dz * dz).sqrt()) * 1e-9;
                    
                    let thickness_m = thickness_nm as f64 * 1e-9;
                    let width_m = width_nm as f64 * 1e-9;
                    let cross_section_m2 = width_m * thickness_m;
                    
                    if cross_section_m2 <= 0.0 {
                        return Err(format!("Invalid cross-section for net '{}'", net_name).into());
                    }
                    
                    let resistance_ohm = resistivity * (length_m / cross_section_m2);
                    
                    eprintln!("[NETLIST PARASITIC DEBUG] Net '{}' seg {}: R = {}Ω (length={}m, area={}m²)", 
                        net_name, seg_num, resistance_ohm, length_m, cross_section_m2);
                    
                    if resistance_ohm > 0.001 {
                        eprintln!("[NETLIST PARASITIC DEBUG] Net '{}' seg {}: Adding trace resistor", net_name, seg_num);
                        graph.parasitics.push(ParasiticElement::TraceResistor {
                            name: format!("Rtr_{}_{}", net_name, seg_num),
                            node_a: prev_node.clone(),
                            node_b: node_end.clone(),
                            value_ohms: resistance_ohm,
                        });
                    } else {
                        eprintln!("[NETLIST PARASITIC DEBUG] Net '{}' seg {}: Resistance too small, skipping", net_name, seg_num);
                    }
                    
                    // Extract ground capacitance for horizontal traces
                    if dz.abs() < 1.0 {
                        // Find the dielectric layer beneath this trace to get accurate substrate height and permittivity
                        let trace_z = segment.start.z as f64;  // Use starting Z coordinate
                        
                        // Require stackup layers to be defined
                        if space.stackup_layers.is_empty() {
                            return Err(format!(
                                "SPICE parasitic extraction requires stackup definition for net '{}'", 
                                net_name
                            ).into());
                        }
                        
                        // Search stackup for dielectric layer below trace
                        // Strategy: Find the closest insulator layer with Z_top <= trace_z
                        let mut found_dielectric: Option<(f64, f64)> = None;
                        let mut min_distance = f64::MAX;
                        
                        for layer in &space.stackup_layers {
                            let _layer_z_bottom = layer.z_bottom as f64;
                            let layer_z_top = layer.z_top as f64;
                            
                            // Only consider dielectric layers that are completely below the trace
                            if layer_z_top < trace_z {
                                let mat_id = space.material_registry.get_id(&layer.material_name).ok_or_else(|| {
                                    format!("Material '{}' used in stackup layer '{}' not found in registry", 
                                        layer.material_name, layer.name)
                                })?;
                                
                                if space.material_registry.is_insulator(mat_id) {
                                    let distance = trace_z - layer_z_top;
                                    if distance < min_distance {
                                        // Get thickness and permittivity from this layer
                                        let thickness = (layer.z_top - layer.z_bottom) as f64;
                                        
                                        let material_props = space.material_registry.get_physical_props(mat_id).ok_or_else(|| {
                                            format!("Dielectric material '{}' has no physical properties defined", layer.material_name)
                                        })?;
                                        
                                        let permittivity = material_props.get("relative_permittivity").ok_or_else(|| {
                                            format!("Dielectric material '{}' missing 'relative_permittivity' property.\n\
                                                     Add to material definition:\n\
                                                     properties:\n    relative_permittivity: 3.9", 
                                                layer.material_name)
                                        })?;
                                        
                                        found_dielectric = Some((thickness, permittivity));
                                        min_distance = distance;
                                    }
                                }
                            }
                        }
                        
                        // Only extract ground capacitance if there's a dielectric layer below
                        // (bottom-layer traces have no ground plane below them)
                        if let Some((substrate_height_nm, epsilon_r)) = found_dielectric {
                            let substrate_height_m = substrate_height_nm * 1e-9;
                            let area_m2 = width_m * length_m;
                            let capacitance_f = EPS_0 * epsilon_r * (area_m2 / substrate_height_m);
                            
                            if capacitance_f > 1e-17 {
                                // Phase 1b Item 3: Dynamic Substrate/Bulk Net Mapping
                                // Use the substrate_net declared in the profile
                                // NO FALLBACK - profile MUST declare substrate_net
                                graph.parasitics.push(ParasiticElement::GroundCapacitance {
                                    name: format!("Cgnd_{}_{}", net_name, seg_num),
                                    node: node_end.clone(),
                                    ref_node: substrate_net.to_string(),
                                    value_farads: capacitance_f,
                                });
                            }
                        }
                        // If no dielectric below, silently skip ground capacitance extraction
                        // This is correct behavior for bottom-layer routing
                    }
                }
            }
            
            prev_node = node_end;
        }
        
        // Map all devices on this net to the LOGICAL NET NAME
        // Devices connect to the logical net (e.g., "In", "Out"),
        // NOT to intermediate parasitic nodes (e.g., "nIn_dev").
        // This ensures clean SPICE output: RR1 In Out 1400.00
        if let Some(netlist) = physical_netlist {
            for device in &netlist.devices {
                for (terminal, terminal_net) in &device.terminals {
                    if terminal_net == net_name {
                        let key = (device.name.to_string(), terminal.to_string());
                        // Use the logical net name, not the intermediate physical node
                        graph.device_nodes.insert(key, net_name.clone());
                    }
                }
            }
        }
    }
    
    Ok(graph)
}

/// Determines if a voltage source should be generated for a net based on module pin direction.
///
/// **Zero-Magic Rule for SPICE Stimulus Generation:**
/// - Input pins / Power nets → Generate driving source
/// - Ground pins / Ground nets → Generate ground reference (0V)
/// - Output pins / Signal nets → DO NOT generate source (circuit-determined)
///
/// **Semantic Rule:**
/// `potential:` on an output/signal net is an Expected Operating Constraint for DRC/LVS,
/// NOT an active driving source. Generating a voltage source on an output would short-circuit
/// the resistor network and destroy the simulation.
fn should_generate_voltage_source(
    net_decl: &hwc_parser::NetDeclaration,
    module_def: Option<&hwc_parser::ModuleDefinition>,
) -> bool {
    use hwc_parser::{NetClassification, PinDirection};

    // Rule 1: Ground nets always get a ground reference (0V source)
    if net_decl.classification == NetClassification::Ground {
        return true;
    }

    // Rule 2: Power nets always get a driving source
    if net_decl.classification == NetClassification::Power {
        return true;
    }

    // Rule 3: If there's a module definition, check pin direction
    if let Some(module) = module_def {
        // Find the pin that corresponds to this net
        for pin in &module.pins {
            if pin.name.as_str() == net_decl.name.as_str() {
                return match pin.direction {
                    PinDirection::Input => true,    // Input pins need driving sources
                    PinDirection::Power => true,     // Power pins need driving sources
                    PinDirection::Ground => true,    // Ground pins need ground references
                    PinDirection::Output => false,   // Output pins are circuit-determined
                    PinDirection::Inout => true,     // Bidirectional pins get sources (can be overridden later)
                    PinDirection::Passive => false,  // Passive pins are circuit-determined
                };
            }
        }
    }

    // Rule 4: Artist Mode (no module) - only generate sources for power/ground classification
    // Signal nets without module context are assumed to be internal/circuit-determined
    false
}

/// Generate stimulus section based on mode
fn generate_stimulus(
    space_def: Option<&hwc_parser::SpaceDefinition>,
    mode: StimulusMode,
    _physical_netlist: Option<&hwc_compiler::alignment::PhysicalNetlist>,
    unit_registry: &hwc_types::UnitRegistry,
    physical_graph: &PhysicalNetlistGraph,
    symbol_table: Option<&SymbolTable>,
) -> String {
    let mut stimulus = String::new();

    // Get module definition if the space implements a module
    let module_def = space_def
        .and_then(|space| space.implements_module.as_ref())
        .and_then(|module_name| {
            symbol_table.and_then(|st| st.get_module(module_name).ok())
        });

    match mode {
        StimulusMode::DcOperatingPoint => {
            // Generate DC voltage sources from net declarations
            if let Some(space_def) = space_def {
                for net_decl in &space_def.nets {
                    if let Some(ref potential) = net_decl.potential {
                        // Check if this net should have a voltage source based on module pin direction
                        if should_generate_voltage_source(net_decl, module_def) {
                            match potential.to_millivolts(unit_registry) {
                                Ok(voltage_mv) => {
                                    let net_name = net_decl.name.as_str();
                                    let voltage_v = voltage_mv as f64 / 1000.0;
                                    
                                    // Use physical entry node if routing exists
                                    let node_name = physical_graph.net_entry_points
                                        .get(net_name)
                                        .map(|s| s.as_str())
                                        .unwrap_or(net_name);
                                    
                                    stimulus.push_str(&format!("V_{} {} 0 DC {:.3}\n", net_name, node_name, voltage_v));
                                }
                                Err(e) => {
                                    eprintln!("Warning: Skipping voltage source for net '{}': {}", net_decl.name, e);
                                }
                            }
                        }
                    }
                }
            }
            stimulus.push_str(".op\n");
        }
        StimulusMode::Transient => {
            // Generate voltage sources for transient analysis
            if let Some(space_def) = space_def {
                for net_decl in &space_def.nets {
                    if let Some(ref potential) = net_decl.potential {
                        // Check if this net should have a voltage source based on module pin direction
                        if should_generate_voltage_source(net_decl, module_def) {
                            match potential.to_millivolts(unit_registry) {
                                Ok(voltage_mv) => {
                                    let net_name = net_decl.name.as_str();
                                    let voltage_v = voltage_mv as f64 / 1000.0;
                                    
                                    // Use physical entry node if routing exists
                                    let node_name = physical_graph.net_entry_points
                                        .get(net_name)
                                        .map(|s| s.as_str())
                                        .unwrap_or(net_name);
                                    
                                    // Generate DC sources (not PULSE) unless explicitly configured otherwise
                                    stimulus.push_str(&format!("V_{} {} 0 DC {:.3}\n", net_name, node_name, voltage_v));
                                }
                                Err(e) => {
                                    eprintln!("[STIMULUS ERROR] Failed to convert potential for net '{}': {}", net_decl.name, e);
                                }
                            }
                        }
                    }
                }
            }
            stimulus.push_str(".tran 200ns\n");
            
            // Don't use .plot - LTspice ignores it
            // Instead, we'll generate a .plt file separately for automatic waveform display
        }
    }

    stimulus
}

/// Generate the circuit body (devices and nets) - reused by all SPICE variants
fn generate_circuit_body(
    space: &HardwareSpace,
    symbol_table: &SymbolTable,
    physical_netlist: Option<&hwc_compiler::alignment::PhysicalNetlist>,
    physical_graph: &PhysicalNetlistGraph,
) -> Result<String, Box<dyn std::error::Error>> {
    let mut netlist_str = String::new();
    
    eprintln!("[NETLIST DEBUG] physical_netlist is_some: {}", physical_netlist.is_some());
    if let Some(ref netlist) = physical_netlist {
        eprintln!("[NETLIST DEBUG] physical_netlist.devices.len(): {}", netlist.devices.len());
    }
    
    // **Stage 1 PDK Subcircuit Cards**
    // Emit .subckt definitions for PDK models used by devices
    // This section comes first so subcircuits are defined before they're instantiated
    if let Some(netlist) = physical_netlist {
        let mut emitted_subcircuits = rustc_hash::FxHashSet::default();
        
        for device in &netlist.devices {
            let device_type_name = netlist
                .device_registry
                .get_name(device.device_type_id)
                .ok_or_else(|| format!("Device '{}' has invalid device_type_id", device.name))?;
            
            if let Ok(device_def) = symbol_table.get_device(device_type_name) {
                if let Some(spice_info) = device_def.spice_info() {
                    if let Some(ref subcircuit_name) = spice_info.subcircuit {
                        // Only emit each subcircuit definition once
                        if emitted_subcircuits.insert(subcircuit_name.clone()) {
                            netlist_str.push_str("* ========================================\n");
                            netlist_str.push_str(&format!("* PDK SUBCIRCUIT: {}\n", subcircuit_name));
                            netlist_str.push_str("* ========================================\n");
                            
                            // Look up the subcircuit definition in the symbol table
                            if let Ok(subckt_def) = symbol_table.get_subcircuit(subcircuit_name.as_str()) {
                                // Generate SPICE from typed AST
                                generate_spice_subcircuit(&mut netlist_str, subckt_def)?;
                                netlist_str.push('\n');
                            } else {
                                // Subcircuit referenced but not defined - this is an error
                                return Err(format!(
                                    "Device '{}' references subcircuit '{}' which is not defined.\n\
                                     \n\
                                     Add to your PDK file:\n\
                                     \n\
                                     subcircuit {}:\n\
                                         terminals: [{}]\n\
                                         parameters: [W = 1.0um, L = 1.0um]\n\
                                         elements:\n\
                                             R1: Resistor(nodes: [PLUS, MINUS], value: ...)\n\
                                             ...",
                                    device.name,
                                    subcircuit_name,
                                    subcircuit_name,
                                    spice_info.terminal_order.join(", ")
                                ).into());
                            }
                        }
                    }
                }
            }
        }
    }

    // Emit nets as comments for reference
    let net_count = space.netlist.num_nets();

    // Collect nets from pours
    let mut pour_nets: rustc_hash::FxHashSet<CompactString> = rustc_hash::FxHashSet::default();
    for pour in &space.pours {
        if let Some(ref net_name) = pour.net {
            pour_nets.insert(net_name.clone());
        }
    }

    let total_nets = net_count + pour_nets.len();

    if total_nets > 0 {
        netlist_str.push_str("* ========================================\n");
        netlist_str.push_str("* NETS\n");
        netlist_str.push_str("* ========================================\n");

        // Emit nets from pours (silicon regions, metal layers)
        // Group merged regions together for parasitic extraction
        let mut merged_regions: rustc_hash::FxHashMap<
            CompactString,
            Vec<&hwc_engine::space::PourMetadata>,
        > = rustc_hash::FxHashMap::default();
        let mut standalone_pours = Vec::new();

        for pour in &space.pours {
            if let Some(ref merged_id) = pour.merged_region_id {
                merged_regions
                    .entry(merged_id.clone())
                    .or_default()
                    .push(pour);
            } else {
                standalone_pours.push(pour);
            }
        }

        // Emit merged regions (treat as single electrical node)
        for (merged_id, pours) in &merged_regions {
            if let Some(first_pour) = pours.first() {
                if let Some(ref net_name) = first_pour.net {
                    // Calculate total area for merged region
                    let total_area: i64 = pours.iter().map(|p| p.area_nm2).sum();

                    netlist_str.push_str(&format!(
                        "* Net: {} (merged region: {}, {} instances, total area: {} nm², material: {}, z: {:.4}mm)\n",
                        net_name,
                        merged_id,
                        pours.len(),
                        total_area,
                        first_pour.material_name,
                        first_pour.z_bottom_nm as f64 / 1_000_000.0
                    ));
                    netlist_str
                        .push_str("*   Parasitic extraction: Treat as single electrical node\n");
                }
            }
        }

        // Emit standalone pours
        for pour in standalone_pours {
            if let Some(ref net_name) = pour.net {
                netlist_str.push_str(&format!(
                    "* Net: {} (pour: {}, material: {}, z: {:.4}mm)\n",
                    net_name,
                    pour.name,
                    pour.material_name,
                    pour.z_bottom_nm as f64 / 1_000_000.0
                ));
            }
        }

        // Emit nets from netlist arena (discrete component connections)
        for net_id in space.netlist.all_net_ids() {
            if let Some(net) = space.netlist.get_net(net_id) {
                let material_name = space
                    .material_registry
                    .get_name(net.material)
                    .unwrap_or("Unknown");
                netlist_str.push_str(&format!(
                    "* Net: {} (width={}nm, material={})\n",
                    net.name, net.width_nm, material_name
                ));

                // List connected pins
                if !net.pins.is_empty() {
                    netlist_str.push_str("*   Connected pins:\n");
                    for pin_id in &net.pins {
                        if let Some(pin) = space.netlist.get_pin(*pin_id) {
                            if let Some(comp) = space.netlist.get_component(pin.parent_component) {
                                netlist_str
                                    .push_str(&format!("*     - {}.{}\n", comp.name, pin.name));
                            }
                        }
                    }
                }
            }
        }
        netlist_str.push('\n');
    }

    // Emit components as SPICE devices
    // If a physical netlist is present, skip schematic-level components to avoid
    // conflicting with extracted M devices (prevents LTspice subcircuit conflicts)
    let is_physical_mode = physical_netlist.is_some();
    let component_count = space.netlist.component_count();
    if component_count > 0 && !is_physical_mode {
        netlist_str.push_str("* ========================================\n");
        netlist_str.push_str("* COMPONENTS (Schematic-Level Subcircuits)\n");
        netlist_str.push_str("* ========================================\n");

        for i in 0..component_count {
            let comp_id = hwc_engine::netlist::ComponentId::new(i as u32);
            if let Some(component) = space.netlist.get_component(comp_id) {
                // Get component pins
                let pins = space.netlist.get_component_pins(comp_id);

                // Build net list for this component
                // v0.1.6 Item #13: Use pin net assignments from entity graph (from net: block)
                let mut net_names = Vec::new();
                for pin_id in &pins {
                    if let Some(pin) = space.netlist.get_pin(*pin_id) {
                        // First, try to get net assignment from entity graph component pins
                        // (these come from the net: block in component placement)
                        let entity_graph_net = space
                            .entity_graph
                            .get_component_pins()
                            .iter()
                            .find(|vp| {
                                vp.component_name == component.name && vp.pin_name == pin.name
                            })
                            .and_then(|vp| vp.net.clone());

                        if let Some(net_name) = entity_graph_net {
                            // Use net assignment from net: block
                            net_names.push(net_name);
                        } else if let Some(net_id) = pin.connected_net {
                            // Fall back to netlist arena connection (from routing)
                            if let Some(net) = space.netlist.get_net(net_id) {
                                net_names.push(net.name.clone());
                            } else {
                                net_names.push(format!("node_{}", net_id.raw()).into());
                            }
                        } else {
                            // No connection - floating pin
                            net_names.push(format!("nc_{}", pin_id.raw()).into());
                        }
                    }
                }

                // Emit SPICE device based on component type
                match component.component_type.to_uppercase().as_str() {
                    "NMOS" | "PMOS" => {
                        // MOSFET: M<name> <drain> <gate> <source> <bulk> <model>
                        // Assume pin order: Gate, Source, Drain, Bulk
                        if net_names.len() >= 3 {
                            let gate = net_names.first().cloned().unwrap_or_else(|| "0".into());
                            let source = net_names.get(1).cloned().unwrap_or_else(|| "0".into());
                            let drain = net_names.get(2).cloned().unwrap_or_else(|| "0".into());
                            let bulk = net_names.get(3).cloned().unwrap_or_else(|| "0".into());

                            netlist_str.push_str(&format!(
                                "M{} {} {} {} {} {}\n",
                                component.name, drain, gate, source, bulk, component.component_type
                            ));
                        } else {
                            netlist_str.push_str(&format!(
                                "* WARNING: {} has insufficient pins for MOSFET\n",
                                component.name
                            ));
                        }
                    }
                    _ => {
                        // Generic subcircuit: X<name> <nets...> <type>
                        netlist_str.push_str(&format!(
                            "X{} {} {}\n",
                            component.name,
                            net_names.join(" "),
                            component.component_type
                        ));
                    }
                }
            }
        }
        netlist_str.push('\n');
    }

    // GAP 7 Phase 4: EXTRACTED DEVICES (Intent-Based Atom Architecture)
    // Devices are extracted from explicit device: bindings during alignment validation
    // This section outputs devices using their SPICE metadata from device definitions
    
    if let Some(netlist) = physical_netlist {
        if !netlist.devices.is_empty() {
            netlist_str.push_str("\n* ========================================\n");
            netlist_str.push_str("* EXTRACTED DEVICES\n");
            netlist_str.push_str("* ========================================\n");

            for device in &netlist.devices {
                // Get device type name from the registry
                let device_type_name = netlist
                    .device_registry
                    .get_name(device.device_type_id)
                    .ok_or_else(|| {
                        format!(
                            "Device '{}' has invalid device_type_id: {}",
                            device.name, device.device_type_id
                        )
                    })?;

                // Look up device definition from symbol table to get SPICE metadata
                let device_def = symbol_table.get_device(device_type_name).map_err(|e| {
                    format!(
                        "Device '{}' of type '{}' not found in symbol table: {}",
                        device.name, device_type_name, e
                    )
                })?;

                // Get SPICE export info - ERROR if not defined
                let spice_info = device_def.spice_info().ok_or_else(|| {
                    format!(
                        "Device '{}' of type '{}' has no SPICE export metadata.\n\
                         \n\
                         Add a 'spice:' block to the device definition:\n\
                         \n\
                         device {}:\n\
                             terminals: [...]\n\
                             materials: ...\n\
                             spice:\n\
                                 prefix: <char>  # R, C, L, M, D, etc.\n\
                                 terminal_order: [terminal1, terminal2, ...]\n\
                                 parameters: [param1, param2, ...]  # optional\n\
                                 model: ModelName  # optional",
                        device.name, device_type_name, device_type_name
                    )
                })?;

                // Build SPICE card using metadata from device definition
                // If subcircuit is defined, use X prefix and subcircuit call
                // Otherwise use the device's prefix directly
                if let Some(ref _subcircuit_name) = spice_info.subcircuit {
                    // PDK subcircuit mode: XR1 n1 n2 nGND sky130_fd_pr__res_high_po W=1.0u L=4.0u
                    netlist_str.push('X');
                    netlist_str.push_str(&device.name);
                } else {
                    // Direct device mode: R1 n1 n2 1000
                    netlist_str.push(spice_info.prefix);
                    netlist_str.push_str(&device.name);
                }

                // Add terminals using physical nodes from the graph
                for terminal_name in &spice_info.terminal_order {
                    // Zero Compiler Magic: FAIL LOUDLY if terminal is unbound
                    // Every terminal in terminal_order MUST have an explicit binding
                    let key = (device.name.to_string(), terminal_name.to_string());
                    let physical_node = if let Some(node) = physical_graph.device_nodes.get(&key) {
                        node.clone()
                    } else {
                        // Fallback to logical net name if no physical node
                        device.terminals.get(terminal_name.as_str())
                            .ok_or_else(|| format!(
                                "\n❌ UNBOUND DEVICE TERMINAL\n\
                                 \nDevice '{}' (type: {}) requires terminal '{}' in its SPICE terminal_order.\n\
                                 \nRequired terminals: {:?}\n\
                                 Available bindings: {:?}\n\
                                 \n💡 FIX: Add an explicit binding in your layout:\n\
                                 \n   add pour(...) named {}_{} on layer: ...:\n\
                                        device: {}.{}\n\
                                        net: <your_net_name>  # e.g., GND for BULK terminals\n\
                                 \n📖 Zero Compiler Magic: HardwareScript never guesses terminal connections.\n\
                                    Every terminal must be explicitly declared by the user.\n",
                                device.name, device_type_name, terminal_name,
                                spice_info.terminal_order,
                                device.terminals.keys().collect::<Vec<_>>(),
                                device.name, terminal_name,
                                device.name, terminal_name
                            ))?.to_string()
                    };
                    
                    netlist_str.push(' ');
                    netlist_str.push_str(&physical_node);
                }

                // Add subcircuit name and parameters if in subcircuit mode
                if let Some(ref subcircuit_name) = spice_info.subcircuit {
                    // PDK Subcircuit Mode: XR1 n1 n2 GND sky130_fd_pr__res_high_po W=1.0u L=4.0u
                    // Get the subcircuit definition to know all terminals
                    let subcircuit_def = symbol_table.get_subcircuit(subcircuit_name)
                        .map_err(|e| format!(
                            "Device '{}' references subcircuit '{}' which is not defined: {}",
                            device.name, subcircuit_name, e
                        ))?;
                    
                    netlist_str.push(' ');
                    netlist_str.push_str(subcircuit_name);
                    
                    // Add subcircuit parameters using named style (W=1.0u L=4.0u)
                    // These come from the device's calculated geometry
                    for param in &subcircuit_def.parameters {
                        let param_value = device.parameters.get(param.name.as_str()).ok_or_else(|| {
                            format!(
                                "Device '{}' missing parameter '{}' required by subcircuit '{}'",
                                device.name, param.name, subcircuit_name
                            )
                        })?;
                        
                        // Format with SI prefix (u for micro, m for milli, etc.)
                        netlist_str.push_str(&format!(" {}={:.2}u", param.name, param_value));
                    }
                } else if let Some(ref model) = spice_info.model_name {
                    // Add model name if specified (and not in subcircuit mode)
                    netlist_str.push(' ');
                    netlist_str.push_str(model);
                    
                    // Add parameters for non-subcircuit devices
                    for param_name in &spice_info.parameters {
                        let param_value = device.parameters.get(param_name.as_str()).ok_or_else(|| {
                            format!(
                                "Device '{}' missing required parameter '{}' (device type: {})",
                                device.name, param_name, device_type_name
                            )
                        })?;
                        
                        match spice_info.parameter_style {
                            SpiceParameterStyle::Positional => {
                                // Positional values: R1 n1 n2 1000
                                if param_value.abs() < 1e-3 || param_value.abs() > 1e6 {
                                    netlist_str.push_str(&format!(" {:.2e}", param_value));
                                } else {
                                    netlist_str.push_str(&format!(" {:.2}", param_value));
                                }
                            }
                            SpiceParameterStyle::Named => {
                                // Named parameters: M1 d g s b NMOS W=1u L=0.18u
                                netlist_str.push_str(&format!(" {}={:.2}u", param_name, param_value));
                            }
                        }
                    }
                } else {
                    // Flat device mode (no model, no subcircuit) - just parameters
                    for param_name in &spice_info.parameters {
                        let param_value = device.parameters.get(param_name.as_str()).ok_or_else(|| {
                            format!(
                                "Device '{}' missing required parameter '{}' (device type: {})",
                                device.name, param_name, device_type_name
                            )
                        })?;
                        
                        match spice_info.parameter_style {
                            SpiceParameterStyle::Positional => {
                                // Positional values: R1 n1 n2 1000
                                if param_value.abs() < 1e-3 || param_value.abs() > 1e6 {
                                    netlist_str.push_str(&format!(" {:.2e}", param_value));
                                } else {
                                    netlist_str.push_str(&format!(" {:.2}", param_value));
                                }
                            }
                            SpiceParameterStyle::Named => {
                                // Named parameters: M1 d g s b NMOS W=1u L=0.18u
                                netlist_str.push_str(&format!(" {}={:.2}u", param_name, param_value));
                            }
                        }
                    }
                }

                netlist_str.push('\n');
            }
            netlist_str.push('\n');
        }
        
        // Emit parasitics integrated into the netlist
        eprintln!("[NETLIST PARASITIC DEBUG] About to check if parasitics should be written: {} parasitics", physical_graph.parasitics.len());
        if !physical_graph.parasitics.is_empty() {
            eprintln!("[NETLIST PARASITIC DEBUG] Writing {} parasitics to SPICE netlist", physical_graph.parasitics.len());
            netlist_str.push_str("* ========================================\n");
            netlist_str.push_str("* INTEGRATED TRACE PARASITICS\n");
            netlist_str.push_str("* ========================================\n");
            
            for parasitic in &physical_graph.parasitics {
                match parasitic {
                    ParasiticElement::TraceResistor { name, node_a, node_b, value_ohms } => {
                        netlist_str.push_str(&format!("* Trace resistance\n"));
                        netlist_str.push_str(&format!("R{} {} {} {:.6e}\n", name, node_a, node_b, value_ohms));
                    }
                    ParasiticElement::GroundCapacitance { name, node, ref_node, value_farads } => {
                        netlist_str.push_str(&format!("* Ground capacitance\n"));
                        netlist_str.push_str(&format!("C{} {} {} {:.6e}\n", name, node, ref_node, value_farads));
                    }
                }
            }
            
            netlist_str.push_str(&format!("\n* Total parasitic elements: {}\n", physical_graph.parasitics.len()));
            netlist_str.push('\n');
        }
    } else {
        // No physical netlist available (Artist Mode or no device bindings)
        println!("   ├─ Device extraction skipped (requires module with explicit bindings)");
        println!("   ├─ Use 'device: DeviceName.terminal' to bind pours to devices");
        netlist_str.push_str("* ========================================\n");
        netlist_str.push_str("* DEVICE EXTRACTION REQUIRES EXPLICIT BINDINGS\n");
        netlist_str.push_str("* Use 'device: DeviceName.terminal' property\n");
        netlist_str.push_str("* ========================================\n\n");
    }

    Ok(netlist_str)
}



/// Generate SPICE subcircuit from typed AST
///
/// Converts the compositional SubcircuitDefinition into SPICE netlist format.
/// This replaces the old raw string body emission with proper code generation.
fn generate_spice_subcircuit(
    output: &mut String,
    subckt: &hwc_parser::SubcircuitDefinition,
) -> Result<(), String> {
    
    
    // Generate .subckt header
    output.push_str(".subckt ");
    output.push_str(&subckt.name.name);
    
    // Add terminals
    for terminal in &subckt.terminals {
        output.push(' ');
        output.push_str(terminal);
    }
    
    // Add parameters with defaults
    for param in &subckt.parameters {
        output.push(' ');
        output.push_str(&param.name);
        output.push('=');
        
        // Format default value
        if let Some(ref default) = param.default_value {
            format_expression_for_spice(output, default)?;
        } else {
            output.push_str("1"); // SPICE requires a default
        }
    }
    
    output.push('\n');
    
    // Generate circuit elements
    for element in &subckt.elements {
        generate_spice_element(output, element)?;
    }
    
    // Generate .ends footer
    output.push_str(".ends ");
    output.push_str(&subckt.name.name);
    output.push('\n');
    
    Ok(())
}

/// Generate a single SPICE element from the typed AST
///
/// Uses the element_type to determine the SPICE prefix and format.
/// This is compositional - it doesn't hardcode which types are valid.
fn generate_spice_element(
    output: &mut String,
    element: &hwc_parser::SubcircuitElement,
) -> Result<(), String> {
   
    
    // Determine SPICE prefix from element type
    let prefix = match element.element_type.chars().next() {
        Some('R') => 'R', // Resistor
        Some('C') => 'C', // Capacitor
        Some('L') => 'L', // Inductor
        Some('V') => 'V', // Voltage source
        Some('I') => 'I', // Current source
        Some('M') => 'M', // MOSFET
        Some('X') => 'X', // Subcircuit instance
        Some('D') => 'D', // Diode
        Some('Q') => 'Q', // BJT
        _ => {
            // Default: use first character of element type
            element.element_type.chars().next().unwrap_or('X')
        }
    };
    
    // Emit: <prefix><name> <nodes...> <params...>
    output.push(prefix);
    output.push_str(&element.name);
    
    // Add nodes
    for node in &element.nodes {
        output.push(' ');
        output.push_str(&node.to_spice());
    }
    
    // Add parameters
    for (param_name, param_value) in &element.parameters {
        output.push(' ');
        
        // For simple "value" parameter, emit value directly
        // For named parameters, emit name=value
        if param_name == "value" {
            format_expression_for_spice(output, param_value)?;
        } else {
            output.push_str(param_name);
            output.push('=');
            format_expression_for_spice(output, param_value)?;
        }
    }
    
    output.push('\n');
    
    Ok(())
}

/// Format an expression for SPICE output
///
/// Converts HardwareScript expressions to SPICE-compatible format.
/// Handles units, arithmetic, and parameters.
fn format_expression_for_spice(
    output: &mut String,
    expr: &hwc_parser::Expression,
) -> Result<(), String> {
    use hwc_parser::{BinaryOperator, Expression, UnaryOperator};
    
    match expr {
        Expression::Literal { value, .. } => {
            output.push_str(&format!("{}", value));
        }
        Expression::FloatLiteral { value, .. } => {
            output.push_str(&format!("{}", value));
        }
        Expression::Measurement { value, unit, .. } => {
            // Convert to SPICE units
            let spice_value = convert_to_spice_units(*value, unit)?;
            output.push_str(&spice_value);
        }
        Expression::Variable { name, .. } => {
            // Parameter reference - emit as-is
            output.push_str(name);
        }
        Expression::Binary { left, operator, right, .. } => {
            // SPICE uses curly braces for expressions: {L / W}
            output.push('{');
            format_expression_for_spice(output, left)?;
            output.push(' ');
            output.push_str(match operator {
                BinaryOperator::Add => "+",
                BinaryOperator::Subtract => "-",
                BinaryOperator::Multiply => "*",
                BinaryOperator::Divide => "/",
                _ => return Err(format!("Unsupported operator {:?} in SPICE expression", operator)),
            });
            output.push(' ');
            format_expression_for_spice(output, right)?;
            output.push('}');
        }
        Expression::Unary { operator, operand, .. } => {
            match operator {
                UnaryOperator::Negate => output.push('-'),
                UnaryOperator::Plus => output.push('+'),
                _ => return Err(format!("Unsupported unary operator {:?} in SPICE", operator)),
            }
            format_expression_for_spice(output, operand)?;
        }
        Expression::Grouped { expression, .. } => {
            output.push('(');
            format_expression_for_spice(output, expression)?;
            output.push(')');
        }
        _ => {
            return Err(format!("Unsupported expression type in SPICE generation: {:?}", expr));
        }
    }
    
    Ok(())
}

/// Convert measurement to SPICE units
///
/// Uses the Unit's to_spice_suffix() method instead of hardcoded pattern matching.
/// This fails loudly if a unit doesn't have a SPICE representation.
fn convert_to_spice_units(value: f64, unit: &hwc_parser::Unit) -> Result<String, String> {
    let suffix = unit.to_spice_suffix()?;
    Ok(format!("{}{}", value, suffix))
}
