//! Netlist Export (SPICE Format)
//!
//! Generates SPICE netlists from the routing graph for circuit simulation.
//! SPICE (Simulation Program with Integrated Circuit Emphasis) is the industry
//! standard format for analog circuit simulation.
//!
//! # GAP 7 Phase 1 Integration
//!
//! Device extraction now returns a structured PhysicalNetlist instead of SPICE text.
//! This enables alignment validation while keeping SPICE export as a formatting step.

use compact_str::CompactString;
use hwc_compiler::SymbolTable;
use hwc_engine::HardwareSpace;
use std::path::Path;

/// Generate SPICE netlist from HardwareSpace
pub fn export(
    space: &HardwareSpace,
    _symbol_table: &SymbolTable,
    output_dir: &Path,
    physical_netlist: Option<&hwc_compiler::alignment::PhysicalNetlist>,
) -> Result<(), Box<dyn std::error::Error>> {
    let path = output_dir.join("netlist.sp");

    let mut netlist_str = String::new();

    // Header
    netlist_str.push_str(&format!(
        "* Hardware Script Native Netlist: {}\n",
        space.name
    ));
    netlist_str.push_str("* Generated by hwc v0.1.6 (Syntax Unification)\n");
    netlist_str.push_str("* Format: SPICE3\n\n");

    // Emit nets as comments for reference
    let net_count = space.netlist.num_nets();

    // Collect nets from pours
    let mut pour_nets: rustc_hash::FxHashSet<CompactString> = rustc_hash::FxHashSet::default();
    for pour in &space.pours {
        if let Some(ref net_name) = pour.net {
            pour_nets.insert(net_name.clone());
        }
    }

    let total_nets = net_count + pour_nets.len();

    if total_nets > 0 {
        netlist_str.push_str("* ========================================\n");
        netlist_str.push_str("* NETS\n");
        netlist_str.push_str("* ========================================\n");

        // Emit nets from pours (silicon regions, metal layers)
        // Group merged regions together for parasitic extraction
        let mut merged_regions: rustc_hash::FxHashMap<
            CompactString,
            Vec<&hwc_engine::space::PourMetadata>,
        > = rustc_hash::FxHashMap::default();
        let mut standalone_pours = Vec::new();

        for pour in &space.pours {
            if let Some(ref merged_id) = pour.merged_region_id {
                merged_regions
                    .entry(merged_id.clone())
                    .or_default()
                    .push(pour);
            } else {
                standalone_pours.push(pour);
            }
        }

        // Emit merged regions (treat as single electrical node)
        for (merged_id, pours) in &merged_regions {
            if let Some(first_pour) = pours.first() {
                if let Some(ref net_name) = first_pour.net {
                    // Calculate total area for merged region
                    let total_area: i64 = pours.iter().map(|p| p.area_nm2).sum();

                    netlist_str.push_str(&format!(
                        "* Net: {} (merged region: {}, {} instances, total area: {} nm², material: {}, z: {:.4}mm)\n",
                        net_name,
                        merged_id,
                        pours.len(),
                        total_area,
                        first_pour.material_name,
                        first_pour.z_bottom_nm as f64 / 1_000_000.0
                    ));
                    netlist_str
                        .push_str("*   Parasitic extraction: Treat as single electrical node\n");
                }
            }
        }

        // Emit standalone pours
        for pour in standalone_pours {
            if let Some(ref net_name) = pour.net {
                netlist_str.push_str(&format!(
                    "* Net: {} (pour: {}, material: {}, z: {:.4}mm)\n",
                    net_name,
                    pour.name,
                    pour.material_name,
                    pour.z_bottom_nm as f64 / 1_000_000.0
                ));
            }
        }

        // Emit nets from netlist arena (discrete component connections)
        for net_id in space.netlist.all_net_ids() {
            if let Some(net) = space.netlist.get_net(net_id) {
                let material_name = space
                    .material_registry
                    .get_name(net.material)
                    .unwrap_or("Unknown");
                netlist_str.push_str(&format!(
                    "* Net: {} (width={}nm, material={})\n",
                    net.name, net.width_nm, material_name
                ));

                // List connected pins
                if !net.pins.is_empty() {
                    netlist_str.push_str("*   Connected pins:\n");
                    for pin_id in &net.pins {
                        if let Some(pin) = space.netlist.get_pin(*pin_id) {
                            if let Some(comp) = space.netlist.get_component(pin.parent_component) {
                                netlist_str
                                    .push_str(&format!("*     - {}.{}\n", comp.name, pin.name));
                            }
                        }
                    }
                }
            }
        }
        netlist_str.push('\n');
    }

    // Emit components as SPICE devices
    // If a physical netlist is present, skip schematic-level components to avoid
    // conflicting with extracted M devices (prevents LTspice subcircuit conflicts)
    let is_physical_mode = physical_netlist.is_some();
    let component_count = space.netlist.component_count();
    if component_count > 0 && !is_physical_mode {
        netlist_str.push_str("* ========================================\n");
        netlist_str.push_str("* COMPONENTS (Schematic-Level Subcircuits)\n");
        netlist_str.push_str("* ========================================\n");

        for i in 0..component_count {
            let comp_id = hwc_engine::netlist::ComponentId::new(i as u32);
            if let Some(component) = space.netlist.get_component(comp_id) {
                // Get component pins
                let pins = space.netlist.get_component_pins(comp_id);

                // Build net list for this component
                // v0.1.6 Item #13: Use pin net assignments from VoxelGrid (from net: block)
                let mut net_names = Vec::new();
                for pin_id in &pins {
                    if let Some(pin) = space.netlist.get_pin(*pin_id) {
                        // First, try to get net assignment from VoxelGrid component pins
                        // (these come from the net: block in component placement)
                        let voxel_grid_net = space
                            .entity_graph
                            .get_component_pins()
                            .iter()
                            .find(|vp| {
                                vp.component_name == component.name && vp.pin_name == pin.name
                            })
                            .and_then(|vp| vp.net.clone());

                        if let Some(net_name) = voxel_grid_net {
                            // Use net assignment from net: block
                            net_names.push(net_name);
                        } else if let Some(net_id) = pin.connected_net {
                            // Fall back to netlist arena connection (from routing)
                            if let Some(net) = space.netlist.get_net(net_id) {
                                net_names.push(net.name.clone());
                            } else {
                                net_names.push(format!("node_{}", net_id.raw()).into());
                            }
                        } else {
                            // No connection - floating pin
                            net_names.push(format!("nc_{}", pin_id.raw()).into());
                        }
                    }
                }

                // Emit SPICE device based on component type
                match component.component_type.to_uppercase().as_str() {
                    "NMOS" | "PMOS" => {
                        // MOSFET: M<name> <drain> <gate> <source> <bulk> <model>
                        // Assume pin order: Gate, Source, Drain, Bulk
                        if net_names.len() >= 3 {
                            let gate = net_names.first().cloned().unwrap_or_else(|| "0".into());
                            let source = net_names.get(1).cloned().unwrap_or_else(|| "0".into());
                            let drain = net_names.get(2).cloned().unwrap_or_else(|| "0".into());
                            let bulk = net_names.get(3).cloned().unwrap_or_else(|| "0".into());

                            netlist_str.push_str(&format!(
                                "M{} {} {} {} {} {}\n",
                                component.name, drain, gate, source, bulk, component.component_type
                            ));
                        } else {
                            netlist_str.push_str(&format!(
                                "* WARNING: {} has insufficient pins for MOSFET\n",
                                component.name
                            ));
                        }
                    }
                    _ => {
                        // Generic subcircuit: X<name> <nets...> <type>
                        netlist_str.push_str(&format!(
                            "X{} {} {}\n",
                            component.name,
                            net_names.join(" "),
                            component.component_type
                        ));
                    }
                }
            }
        }
        netlist_str.push('\n');
    }

    // GAP 7 Phase 4: EXTRACTED DEVICES (Intent-Based Atom Architecture)
    // Devices are extracted from explicit device: bindings during alignment validation
    // This section outputs the actual transistors with their SPICE parameters
    if let Some(netlist) = physical_netlist {
        if !netlist.devices.is_empty() {
            netlist_str.push_str("\n* ========================================\n");
            netlist_str.push_str("* EXTRACTED DEVICES (Transistors)\n");
            netlist_str.push_str("* ========================================\n");

            for device in &netlist.devices {
                // Get device type name from the registry stored in PhysicalNetlist
                // This is the device type from the .hw file (e.g., "NMOS", "PMOS", "BJT")
                // which is also the SPICE model name - no translation needed!
                let model_name = netlist
                    .device_registry
                    .get_name(device.device_type_id)
                    .unwrap_or("UNKNOWN");

                // Extract terminal connections
                let drain = device
                    .terminals
                    .get("drain")
                    .cloned()
                    .unwrap_or_else(|| "0".into());
                let gate = device
                    .terminals
                    .get("gate")
                    .cloned()
                    .unwrap_or_else(|| "0".into());
                let source = device
                    .terminals
                    .get("source")
                    .cloned()
                    .unwrap_or_else(|| "0".into());
                let bulk = device
                    .terminals
                    .get("bulk")
                    .cloned()
                    .unwrap_or_else(|| "0".into());

                // Extract parameters (already in micrometers from device extractor)
                let w_um = device
                    .parameters
                    .get("W")
                    .copied()
                    .unwrap_or(1.0);
                let l_um = device
                    .parameters
                    .get("L")
                    .copied()
                    .unwrap_or(1.0);

                // Write MOSFET line: M<name> <drain> <gate> <source> <bulk> <model> W=<w>u L=<l>u
                netlist_str.push_str(&format!(
                    "M{} {} {} {} {} {} W={:.2}u L={:.2}u",
                    device.name, drain, gate, source, bulk, model_name, w_um, l_um
                ));

                // Add parasitic parameters if available
                if let Some(as_val) = device.parameters.get("AS") {
                    netlist_str.push_str(&format!(" AS={:.2e}", as_val));
                }
                if let Some(ad_val) = device.parameters.get("AD") {
                    netlist_str.push_str(&format!(" AD={:.2e}", ad_val));
                }
                if let Some(ps_val) = device.parameters.get("PS") {
                    netlist_str.push_str(&format!(" PS={:.2e}", ps_val));
                }
                if let Some(pd_val) = device.parameters.get("PD") {
                    netlist_str.push_str(&format!(" PD={:.2e}", pd_val));
                }

                netlist_str.push('\n');
            }
            netlist_str.push('\n');
        }
    } else {
        // No physical netlist available (Artist Mode or no device bindings)
        println!("   ├─ Device extraction skipped (requires module with explicit bindings)");
        println!("   ├─ Use 'device: DeviceName.terminal' to bind pours to devices");
        netlist_str.push_str("* ========================================\n");
        netlist_str.push_str("* DEVICE EXTRACTION REQUIRES EXPLICIT BINDINGS\n");
        netlist_str.push_str("* Use 'device: DeviceName.terminal' property\n");
        netlist_str.push_str("* ========================================\n\n");
    }

    // Automatic ground bridge for physical mode (prevents floating GND errors in LTspice)
    if is_physical_mode {
        netlist_str.push_str("* ========================================\n");
        netlist_str.push_str("* AUTOMATIC STIMULUS & MODELS\n");
        netlist_str.push_str("* ========================================\n");
        netlist_str.push_str("Vgnd GND 0 0\n");
    }

    // Footer
    netlist_str.push_str(".end\n");

    std::fs::write(&path, &netlist_str)?;

    let component_count = space.netlist.component_count();
    let pour_net_count = space.pours.iter().filter(|p| p.net.is_some()).count();
    let total_nets = net_count + pour_net_count;

    if component_count > 0 || total_nets > 0 {
        println!(
            "   ✅ Netlist: {} ({} components, {} nets)",
            path.display(),
            component_count,
            total_nets
        );
    } else {
        println!("   ✅ Netlist: {} (no components or nets)", path.display());
    }

    Ok(())
}
