//! Core constraint data structures.
//!
//! This module defines the fundamental types used throughout the constraint
//! management system.

use crate::geometry::Point3D;
use crate::netlist::NetId;
use rustc_hash::FxHashMap;

// ============================================================================
// Phase 1.1: Constraint Data Structures
// ============================================================================

/// Routing constraints for a single net.
///
/// These constraints are calculated from material properties and electrical
/// requirements before routing begins.
#[derive(Debug, Clone)]
pub struct RouteConstraints {
    /// Minimum trace width in nanometers (from IPC-2221 formula)
    pub min_trace_width_nm: i64,

    /// Minimum clearance to other nets in nanometers (from dielectric breakdown)
    pub min_clearance_nm: i64,

    /// Maximum parallel length with other nets in nanometers (from crosstalk)
    pub max_parallel_length_nm: i64,

    /// Maximum resistance in ohms (from electrical requirements)
    pub max_resistance_ohm: f64,

    /// Maximum current in milliamps (from ampacity limits)
    pub max_current_ma: i64,

    /// Target impedance in ohms (for high-speed signals, None for regular traces)
    pub impedance_ohm: Option<f64>,
}

/// Clearance zone around a net (the "forcefield").
///
/// This represents the forbidden zone around a net where other nets cannot route.
/// The zone is calculated from voltage difference and material dielectric strength.
#[derive(Debug, Clone)]
pub struct ClearanceZone {
    /// Which net owns this clearance zone
    pub net_id: NetId,

    /// Voltage of this net in millivolts
    pub voltage_mv: i64,

    /// Radius of the clearance zone in nanometers
    pub clearance_radius_nm: i64,
}

/// Layer-specific routing direction for Manhattan routing.
///
/// Each layer is restricted to one primary direction to prevent self-blocking.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LayerDirection {
    /// North/South routing only (Y-axis)
    NorthSouth,

    /// East/West routing only (X-axis)
    EastWest,

    /// Any direction allowed (power/ground planes)
    Any,
}

/// Stackup constraints for impedance calculations.
///
/// Contains physical layer stackup information needed for calculating
/// trace impedance using microstrip formulas.
#[derive(Debug, Clone)]
pub struct StackupInfo {
    /// Dielectric height above ground plane in nanometers
    pub dielectric_height_nm: i64,

    /// Copper thickness in nanometers
    pub copper_thickness_nm: i64,

    /// Relative permittivity (εr) of the dielectric material
    pub relative_permittivity: f64,

    /// Default target impedance for high-speed signals (optional)
    pub default_impedance_ohm: Option<f64>,
}

/// Fabrication constraints from profile definition.
///
/// These constraints come from the manufacturing process capabilities
/// and are loaded from profile definitions in the Symbol Table.
///
/// **v0.1.4 Addition**: Replaces YAML-based profile loading.
#[derive(Debug, Clone)]
pub struct FabricationConstraints {
    /// Minimum trace width in nanometers
    pub min_trace_width_nm: i64,

    /// Minimum spacing between traces in nanometers
    pub min_trace_spacing_nm: i64,

    /// Minimum via diameter in nanometers
    pub min_via_diameter_nm: i64,

    /// Default via diameter in nanometers
    pub default_via_diameter_nm: i64,

    /// Minimum annular ring around via in nanometers
    pub min_annular_ring_nm: i64,

    /// Minimum spacing between drill holes in nanometers (v0.1.7)
    pub min_spacing_nm: i64,

    /// Low-voltage clearance (<50V) in nanometers
    pub low_voltage_clearance_nm: i64,

    /// Medium-voltage clearance (50-150V) in nanometers
    pub medium_voltage_clearance_nm: i64,

    /// High voltage clearance (>150V) in nanometers
    pub high_voltage_clearance_nm: i64,

    /// Safety factor for clearance calculations (default: 2.0)
    pub safety_factor: f64,

    /// Stackup information for impedance calculations (optional)
    pub stackup: Option<StackupInfo>,

    /// Solder mask expansion in nanometers (v0.1.7)
    /// None: no solder mask expansion declared in profile
    pub solder_mask_expansion_nm: Option<i64>,

    /// Technology type (PCB or ASIC) - REQUIRED field that determines via geometry,
    /// clearance rules, and manufacturing constraints throughout the entire pipeline.
    /// Must be explicitly declared in every profile.
    pub technology: hwc_types::Technology,
}

/// Complete constraint rulebook for the routing engine.
///
/// This is generated by the Constraint Manager before routing begins.
/// It contains all the geometric rules that the router must follow.
#[derive(Debug, Clone)]
pub struct ConstraintRulebook {
    /// Per-net routing constraints
    pub per_net_constraints: FxHashMap<NetId, RouteConstraints>,

    /// Clearance zones for all nets
    pub clearance_zones: Vec<ClearanceZone>,

    /// Layer-specific routing directions (Manhattan routing)
    pub layer_directions: FxHashMap<usize, LayerDirection>,

    /// Coordinate snapping resolution in nanometers
    pub resolution_nm: i64,

    /// Default current for thermal calculations (milliamps)
    /// Used when net-specific current is not available
    pub default_current_ma: Option<i64>,

    /// Fabrication constraints from profile (v0.1.4 Phase 3 addition)
    /// Contains manufacturing limits (trace widths, clearances, via sizes)
    pub fabrication: Option<FabricationConstraints>,
}

impl ConstraintRulebook {
    /// Create a new empty constraint rulebook.
    ///
    /// v0.1.8: No hardcoded defaults for current, temperature, or clearance.
    /// All values must come from the PDK profile. Fail-fast if not provided.
    pub fn new(resolution_nm: i64) -> Self {
        Self {
            per_net_constraints: FxHashMap::default(),
            clearance_zones: Vec::new(),
            layer_directions: FxHashMap::default(),
            resolution_nm,
            default_current_ma: None, // v0.1.8: No default. Fail if current_limit not declared.
            fabrication: None,        // Must come from PDK profile.
        }
    }

    /// Set fabrication constraints from profile.
    ///
    /// **v0.1.4 Phase 3**: Allows DRC validators to access profile-based constraints.
    pub fn set_fabrication_constraints(&mut self, constraints: FabricationConstraints) {
        self.fabrication = Some(constraints);
    }

    /// Get default constraints for nets that don't have specific rules.
    ///
    /// **v0.1.8**: Fabrication constraints are MANDATORY. All values come from
    /// the PDK profile — no silent defaults.
    pub fn get_default_constraints(&self) -> RouteConstraints {
        let fab = self.fabrication.as_ref().expect(
            "ConstraintRulebook: fabrication constraints are required but none are loaded. \
             Declare a profile with 'trace:' and 'clearance:' constraints in the space definition.",
        );

        RouteConstraints {
            min_trace_width_nm: fab.min_trace_width_nm,
            min_clearance_nm: fab.min_trace_spacing_nm,
            max_parallel_length_nm: 0, // Unlimited — no crosstalk limit by default
            max_resistance_ohm: 0.0,   // Unlimited — no resistance limit by default
            max_current_ma: 0,         // Unlimited — no current limit by default
            impedance_ohm: None,       // No impedance control by default
        }
    }

    /// Get constraints for a specific net.
    pub fn get_net_constraints(&self, net_id: NetId) -> Option<&RouteConstraints> {
        self.per_net_constraints.get(&net_id)
    }

    /// Get layer direction for a specific layer.
    pub fn get_layer_direction(&self, layer: usize) -> LayerDirection {
        self.layer_directions
            .get(&layer)
            .copied()
            .unwrap_or(LayerDirection::Any)
    }

    /// Check if a point is in any clearance zone.
    ///
    /// NOTE: Clearance zones are checked analytically during routing via
    /// `check_clearance_violation`. This method is kept for API compatibility
    /// but always returns false.
    pub fn is_in_clearance_zone(&self, _point: Point3D, _net_id: NetId) -> bool {
        false
    }
}
