[package]
name = "hwc-parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
logos = { workspace = true }
thiserror = { workspace = true }
miette = { workspace = true }
rustc-hash = { workspace = true }
compact_str = { workspace = true }
smallvec = { workspace = true }
clipper2-rust = "1.0"
hwc-diagnostics = { path = "../hwc-diagnostics" }
serde = { version = "1.0", features = ["derive"] }
