//! Display implementation for HardwareScript v0.3.0 Token types

use std::fmt;
use super::token_types::Token;

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Token::Identifier(s) => write!(f, "identifier '{}'", s),
            Token::Integer(n) => write!(f, "integer {}", n),
            Token::Float(n) => write!(f, "float {}", n),
            Token::String(s) => write!(f, "string \"{}\"", s),
            Token::Measurement(m) => write!(f, "measurement '{}'", m),
            Token::ImportPath(p) => write!(f, "import path '{}'", p),

            // Brackets and delimiters
            Token::OpenBrace => write!(f, "'{{'"),
            Token::CloseBrace => write!(f, "'}}'"),
            Token::OpenBracket => write!(f, "'['"),
            Token::CloseBracket => write!(f, "']'"),
            Token::OpenParen => write!(f, "'('"),
            Token::CloseParen => write!(f, "')'"),
            Token::Colon => write!(f, "':'"),
            Token::Semicolon => write!(f, "';'"),
            Token::Comma => write!(f, "','"),
            Token::Dot => write!(f, "'.'"),
            Token::Arrow => write!(f, "'->'"),
            Token::FatArrow => write!(f, "'=>'"),
            Token::Underscore => write!(f, "'_'"),

            // Operators
            Token::Equals => write!(f, "'='"),
            Token::PlusEquals => write!(f, "'+='"),
            Token::MinusEquals => write!(f, "'-='"),
            Token::StarEquals => write!(f, "'*='"),
            Token::SlashEquals => write!(f, "'/='"),
            Token::PercentEquals => write!(f, "'%='"),
            Token::Plus => write!(f, "'+'"),
            Token::Hyphen => write!(f, "'-'"),
            Token::Asterisk => write!(f, "'*'"),
            Token::Slash => write!(f, "'/'"),
            Token::Percent => write!(f, "'%'"),
            Token::Ampersand => write!(f, "'&'"),
            Token::Pipe => write!(f, "'|'"),
            Token::Caret => write!(f, "'^'"),
            Token::Tilde => write!(f, "'~'"),
            Token::ShiftLeft => write!(f, "'<<'"),
            Token::ShiftRight => write!(f, "'>>'"),
            Token::DoubleEquals => write!(f, "'=='"),
            Token::NotEquals => write!(f, "'!='"),
            Token::LessThan => write!(f, "'<'"),
            Token::GreaterThan => write!(f, "'>'"),
            Token::LessThanOrEqual => write!(f, "'<='"),
            Token::GreaterThanOrEqual => write!(f, "'>='"),
            Token::Range => write!(f, "'..'"),
            Token::RangeInclusive => write!(f, "'..='"),
            Token::AtSymbol => write!(f, "'@'"),

            // Keywords
            Token::Fn => write!(f, "'fn'"),
            Token::Let => write!(f, "'let'"),
            Token::Mut => write!(f, "'mut'"),
            Token::Const => write!(f, "'const'"),
            Token::Struct => write!(f, "'struct'"),
            Token::Enum => write!(f, "'enum'"),
            Token::If => write!(f, "'if'"),
            Token::Else => write!(f, "'else'"),
            Token::For => write!(f, "'for'"),
            Token::In => write!(f, "'in'"),
            Token::Return => write!(f, "'return'"),
            Token::Break => write!(f, "'break'"),
            Token::Continue => write!(f, "'continue'"),
            Token::Assert => write!(f, "'assert'"),
            Token::Match => write!(f, "'match'"),
            Token::Import => write!(f, "'import'"),
            Token::Export => write!(f, "'export'"),
            Token::From => write!(f, "'from'"),
            Token::True => write!(f, "'true'"),
            Token::False => write!(f, "'false'"),
            Token::And => write!(f, "'and'"),
            Token::Or => write!(f, "'or'"),
            Token::Not => write!(f, "'not'"),
            Token::Space => write!(f, "'space'"),
            Token::Module => write!(f, "'module'"),
            Token::Device => write!(f, "'device'"),
            Token::Material => write!(f, "'material'"),
            Token::Profile => write!(f, "'profile'"),
            Token::Route => write!(f, "'route'"),
            Token::Test => write!(f, "'test'"),
            Token::Implements => write!(f, "'implements'"),
            Token::To => write!(f, "'to'"),

            // Comments and EOF
            Token::DocBlock(_) => write!(f, "doc block"),
            Token::BlockComment(_) => write!(f, "block comment"),
            Token::DocComment(_) => write!(f, "doc comment"),
            Token::Eof => write!(f, "end of file"),
        }
    }
}
