use compact_str::CompactString;
use miette::{IntoDiagnostic, Result};
use std::path::PathBuf;

pub fn execute(name: CompactString, path: Option<PathBuf>) -> Result<()> {
    let project_path = path.unwrap_or_else(|| PathBuf::from(&name));

    println!("📦 Initializing project: {}", name);
    println!("   Path: {}", project_path.display());

    // Create directory structure
    std::fs::create_dir_all(&project_path).into_diagnostic()?;
    std::fs::create_dir_all(project_path.join("src")).into_diagnostic()?;
    std::fs::create_dir_all(project_path.join("build")).into_diagnostic()?;
    std::fs::create_dir_all(project_path.join("materials")).into_diagnostic()?;

    // Create main.hw
    let main_hw = format!(
        r#"// {} - Hardware Script Project
// Generated by hwc init

space Board {{
    dimensions: (100mm, 100mm, 2mm)
    grid: (100, 100, 2)
    substrate: FR4
}}

// Add your components and routes here
"#,
        name
    );

    std::fs::write(project_path.join("src/main.hw"), main_hw).into_diagnostic()?;

    // Create hwc.toml config
    let config = format!(
        r#"[project]
name = "{}"
version = "0.1.0"

[build]
output_dir = "build"
formats = ["glb", "dxf", "netlist"]

[materials]
# Path to custom materials database (optional)
# custom_db = "materials/custom.yaml"
"#,
        name
    );

    std::fs::write(project_path.join("hwc.toml"), config).into_diagnostic()?;

    println!("✅ Project initialized!");
    println!("\nNext steps:");
    println!("  cd {}", name);
    println!("  hwc build src/main.hw");

    Ok(())
}
